[package]
name = "muzak"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dateparser = "0.2.1"
symphonia = { version = "0.5.4", features = ["all", "opt-simd-sse"] }
cpal = "0.15.3"
bitflags = "2.6.0"
ux = "0.1.6"
rubato = "0.15.0"
rb = "0.4.1"
gpui = { git = "https://github.com/zed-industries/zed" }
smallvec = "1.13.2"
rust-embed = "8.5.0"
clap = { version = "4.5.9", features = ["derive"] }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
image = "0.25.1"
ahash = "0.8.11"
sqlx = { version = "0.7", features = ["runtime-async-std", "sqlite", "chrono"] }
async-std = { version = "1.12.0", features = ["attributes"] }
directories = "5.0.1"
