[package]
name = "muzak"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dateparser = "0.2.1"
symphonia = { version = "0.5.4", features = ["all", "opt-simd-sse"] }
cpal = "0.15.3"
bitflags = "2.6.0"
rubato = "0.15.0"
rb = "0.4.1"
gpui = { git = "https://github.com/zed-industries/zed" }
#gpui = { git = "https://github.com/143mailliw/zed", branch = "drop-image" }
#gpui = { path = "../gpui-contrib/zed/crates/gpui" }
smallvec = "1.13.2"
rust-embed = "8.5.0"
clap = { version = "4.5.9", features = ["derive"] }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
image = "0.25.1"
ahash = { version = "0.8.11", features = ["serde"] }
sqlx = { version = "0.7", features = ["runtime-async-std", "sqlite", "chrono"] }
async-std = { version = "1.12.0", features = ["attributes"] }
directories = "5.0.1"
anyhow = "1.0.86"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
moka = { version = "0.12.8", features = ["future"] }
intx = "0.1.0"
rand = { version = "0.8.5" }
notify = "7.0.0"
uuid = "1.11.0"

[target.'cfg(target_os = "linux")'.dependencies]
libpulse-binding = "2.28.1"
libpulse-simple-binding = "2.28.1"
pulsectl-rs = "0.3.2"

[profile.release-distro]
inherits = "release"
lto = true
strip = true
panic = "abort"

[package.metadata.bundle]
name = "Muzak"
identifier = "me.william341.muzak"
