name: macOS (ARM binary)

on:
    push:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: macos-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: cargo install cargo-bundle
            - name: Build
              run: cargo build --verbose --release
            - name: Bundle
              run: cargo bundle --release
            - uses: actions/upload-artifact@v4
              with:
                  name: muzak
                  path: target/release/muzak/bundle/osx/
            - uses: softprops/action-gh-release@v2
              with:
                  files: target/release/muzak/bundle/osx/*
                  prerelease: true
                  name: latest
                  tag_name: latest
