name: Linux (binary)

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pkg-config
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v4
      with:
        name: muzak
        path: target/release/muzak
