name: Windows (binary)

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v4
      with:
        name: muzak
        path: target/release/muzak.exe
